export enum ErrorCode {
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  LESSON_NOT_FOUND = 'LESSON_NOT_FOUND',
  NOT_ENROLLED = 'NOT_ENROLLED',
  ALREADY_ENROLLED = 'ALREADY_ENROLLED',
  CERTIFICATE_ALREADY_ISSUED = 'CERTIFICATE_ALREADY_ISSUED',
  LESSON_ALREADY_COMPLETED = 'LESSON_ALREADY_COMPLETED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  COURSE_ALREADY_EXISTS = 'COURSE_ALREADY_EXISTS',
  COURSE_HAS_CONTENT = 'COURSE_HAS_CONTENT',
  
}
