export enum MessageCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  BAD_REQUEST = 'BAD_REQUEST',
  COURSE_ALREADY_PUBLISHED = 'COURSE_ALREADY_PUBLISHED',
  COURSE_NOT_READY_FOR_REVIEW = 'COURSE_NOT_READY_FOR_REVIEW',
  INVALID_OBJECT_ID = 'INVALID_OBJECT_ID',
  DUPLICATE_KEY = 'DUPLICATE_KEY',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
